### ISSUE TITLE
Error occur periodically

### ISSUE THREAD

**Issue by joze2016** [gosquared/redis-clustr#17]
RedisClustr.js:208:34

error: server crash!s.slice(...).map is not a function TypeError: s.slice(...).map is not a function
    at Command.callback (...\node_modules\redis-clustr\src\RedisClustr.js:208:34)
    at normal_reply (...\node_modules\redis\index.js:714:21)
    at RedisClient.return_reply (...\node_modules\redis\index.js:816:9)
    at JavascriptRedisParser.Parser.returnReply (...\node_modules\redis\index.js:188:18)
    at JavascriptRedisParser.execute (...\node_modules\redis-parser\lib\parser.js:415:12)
    at Socket.<anonymous> (...\node_modules\redis\index.js:267:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)

**Comment by jbt** [comment]
Hi @joze2016 thanks for reporting this! Looks like that's coming up because an unexpected reply is coming back from `CLUSTER SLOTS` (but for some reason it's not returning an error)

Are you able to share any info on your setup - what version of redis / node modules you're using / if there's anything unusual about how the cluster is set up? Would be great to get a failing test case to narrow down what's happening.

In the meanwhile I'll see about adding some extra error catching for bad responses like this so at least it won't crash.

**Comment by joze2016** [comment]
@jbt sorry for late reply.

Our setup info please refer below:
Redis version is 3.2.5
Redis of node modules is 2.6.3
Resis clustr of node modules is 1.5.3

The redis.conf of cluster set up:
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
appendonly yes
save 900 1
save 300 10
save 60 10000

This crash is coming up automatically, we don't do any unusual test case.
