### ISSUE TITLE
TypeError: e.substr is not a function

### ISSUE THREAD

**Issue by aep** [gosquared/redis-clustr#18]
trying to run on nodejs4.3 on aws lambda

````
2016-12-08T20:59:57.703Z	45fb8783-bd89-11e6-9e9a-493023932084	TypeError: e.substr is not a function
    at Command.callback (/var/task/node_modules/redis-cluster/index.js:181:18)
    at RedisClient.return_error (/var/task/node_modules/redis/index.js:559:25)
    at ReplyParser.<anonymous> (/var/task/node_modules/redis/index.js:308:18)
    at emitOne (events.js:77:13)
    at ReplyParser.emit (events.js:169:7)
    at ReplyParser.send_error (/var/task/node_modules/redis/lib/parser/javascript.js:296:10)
    at ReplyParser.execute (/var/task/node_modules/redis/lib/parser/javascript.js:181:22)
    at RedisClient.on_data (/var/task/node_modules/redis/index.js:535:27)
    at Socket.<anonymous> (/var/task/node_modules/redis/index.js:91:14)
    at emitOne (events.js:77:13)
````

**Comment by jbt** [comment]
Hmm, I'm not sure exactly where that's coming from (`e.substr` doesn't match anything around those line numbers). What version of the module are you seeing this with?

**Comment by jbt** [comment]
Just digging around a bit, it looks like that error might be coming from [this line](https://github.com/joaojeronimo/node_redis_cluster/blob/bdc72885bcc76528d7b2659b6a61469a47378ca1/index.js#L181) over on a different redis cluster module - is it possible that's the one you mean?

**Comment by aep** [comment]
wow that's embarrassing. yeah i'm using the totally wrong module. D:
