### ISSUE TITLE
redis-clustr monitor mode crashes

### ISSUE THREAD

**Issue by geogeim** [gosquared/redis-clustr#21]
```
  redisPub.monitor();
  redisPub.on("monitor", function (time, args, raw_reply) {
    log.debug("REDIS", args.join(" "));
  });
```

Unhandled exception has occurred: Error
Error: no key for command: monitor
    at d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\src\RedisClustr.js:362:25
    at module.exports.RedisClustr.parseArgs (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\src\RedisClustr.js:345:11)
    at d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\src\RedisClustr.js:333:12
    at runCbs (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\src\RedisClustr.js:170:7)
    at Command.callback (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\src\RedisClustr.js:254:7)
    at normal_reply (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\node_modules\redis\index.js:721:21)
    at RedisClient.return_reply (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\node_modules\redis\index.js:819:9)
    at JavascriptRedisParser.returnReply (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\node_modules\redis\index.js:192:18)
    at JavascriptRedisParser.execute (d:\Work\ninesix\webtriggers\session\node_modules\redis-parser\lib\parser.js:538:12)
    at Socket.<anonymous> (d:\Work\ninesix\webtriggers\session\node_modules\redis-clustr\node_modules\redis\index.js:274:27)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:559:20)

**Comment by jbt** [comment]
Ah yes `MONITOR` is one command we didn't think about. I guess the logical solution for this is to issue a `MONITOR` to every master instance in the cluster and then combine the triggered `monitor` events.
