### ISSUE TITLE
Why is "MOVED" throwing an exception instead of following it?

### ISSUE THREAD

**Issue by idoromm** [gosquared/redis-clustr#29]
Hey,

Maybe I'm asking a silly question but I couldn't find the answer in the repo.
Basically I have a 3-node cluster with 3 masters/slaves.

I can connect and perform get/set SOMETIMES.... When I get a "MOVED" error the client immediately crashes.

Is there any good way to handle these errors and simply "redirect" to correct slave/master with available/relevant slots?

Thanks!

**Comment by jbt** [comment]
That sounds odd - it should definitely be handling MOVED responses fine - the [handling of MOVED/ASK responses](https://github.com/gosquared/redis-clustr/blob/355325582c8c4a64d36b26ddbae298d6308623ab/src/RedisClustr.js#L424-L436) has never caused crashes before.

Are you able to share any more information about your redis setup (version etc) and what the crash looks like? Is there a stack trace you can share that'll help track down where this crash is coming from?

**Comment by idoromm** [comment]
Hey @jbt , of course I would love to share more information.
My versions are:

"redis": "^2.8.0",
"redis-clustr": "^1.6.0"


Note that the error happens only when there is a MOVE involved, so sometimes I call "set/get" and it works perfectly and sometimes it will throw an error and terminate.
Stacktrace:
After calling `await redisClient.get("543534545354354");` I get:

`stack:"ReplyError: MOVED 13996 xx.xxx.xx.xx:6379\n    at parseError (.../node_modules/redis-parser/lib/parser.js:193:12)\n    at parseType (.../node_modules/redis-parser/lib/parser.js:303:14)"`

It's worth noting that the same commands work perfectly when I run them from Java (using lettuce-io redis).

Relevant JS code:

```
const util = require('util');
var RedisClustr = require('redis-clustr');
var redis = new RedisClustr({
    servers: [{
            host: "xx.xxx.xx.xxx",
            port: 6379
        },
        {
            host: "xx.xxx.xx.xxx",
            port: 6379

        }, {
            host: "xx.xxx.xx.xxx",
            port: 6379

        }
    ], 
    slotInterval: 1000, 
    maxQueueLength: 100, 
    queueShift: false, 
    wait: 5000,
    slaves: 'share',
    createClient: function (port, host, options) {
        return require('redis').createClient(6379, "xx.xxx.xx.xxx", options);
    },
    redisOptions: {

        retry_strategy: function (options) {
            if (options.total_retry_time > 1000 * 60 * 60) {
                return new Error('Total retry time exhausted (1 hour)');
            }
            if (options.attempt > 100) {
                return undefined;
            }
            return Math.min(options.attempt * 100, 3000);
        }
    }
});
```

```
const getAsync = util.promisify(redis.get).bind(redis);
const setAsync = util.promisify(redis.set).bind(redis);

class Redis {
    get(key) {
        return getAsync(key);
    }
    set(key, value) {
        return setAsync(key, value);
    }
}

module.exports = new Redis;
```

**Comment by jbt** [comment]
Ok that's interesting - that should only happen if the cluster sends back MOVED a whole bunch of times. 

The only way I can reproduce this is to have the cluster set up in a weird inconsistent state where different nodes have different opinions of who owns a slot (e.g. node A thinks node B owns slot 13996, but node B thinks node A owns 13996). Obviously that's a very bad state for your cluster to be in - that's certainly not an error we can handle, but it should be possible to detect such a situation.

Do you get the same output for `CLUSTER SLOTS` if you run it on all three of your nodes?
